#!/usr/bin/env bash

# Volume change sound.
declare -r VOLUME_CHANGE_SOUND=${VOLUME_CHANGE_SOUND:-/usr/share/sounds/freedesktop/stereo/audio-volume-change.oga}

# Configuration to decide to play sound or not
declare -r PLAY_SOUND=true

declare -r \
    RESET=$'\033[0m' \
    RED=$'\033[0;31m' \
    BOLD="\e[01m"

declare prev_volume # notify only on volume change 
declare card_change=false # don't play sound on card_change

is_muted() {
    return `pactl get-sink-mute @DEFAULT_SINK@ | grep -q 'yes'`
}

get_volume(){
    echo `pactl get-sink-volume @DEFAULT_SINK@ | awk -W posix '/^Volume: / {gsub("%,?", ""); print $5; exit}'`
}

play_volume_changed(){
    $PLAY_SOUND || return
    paplay -d  @DEFAULT_SINK@ "${VOLUME_CHANGE_SOUND}" & 
}

get_default_sink_index(){
    pactl list sinks | awk -W posix '/^Sink #/{gsub("#", ""); idx = $2}
        /^[ \t]+Name: / {insink = $2 == "'"$(pactl get-default-sink)"'"; if (insink) { print idx }; exit}'
}

check_volnoti_command(){
    cmd="$1"

    command -v "${cmd}" >/dev/null 2>&1 || {
        echo -e "${RED}${BOLD}ERROR"'!!'"${RESET} command ${BOLD}${cmd}${RESET} is missing." >&2
        echo -e "Install ${BOLD}volnoti${RESET} package, that provides it. Aborting." >&2
        exit 1; 
    }
}

check_volnoti_command volnoti-show
check_volnoti_command volnoti

# Start volnoti if not already running
if [ ! `pgrep -n -x volnoti` ]
then
    volnoti
fi

prev_volume=$(get_volume)

while IFS= read -r line; do
    if echo "${line}" | grep -q card
    then
        card_change=true
        continue
    fi
    sink=`echo "${line}" | awk -F# '{print $2}'`
    current_volume=$(get_volume)
    if [ "$current_volume" == "$prev_volume" ] && [ "$card_change" != true ]
    then
        continue
    fi
    # show notifcation on volume change || card change, but play sound only on volume change
    if [ "${sink}" == "$(get_default_sink_index)" ]
    then
        prev_volume=$current_volume

        display_volume=$current_volume
        if((display_volume>100))
        then
            display_volume=100
        fi
        if is_muted
        then
            volnoti-show -m ${display_volume}
        else
            volnoti-show ${display_volume}
            if [ "$card_change" != true ]
            then
                play_volume_changed
            fi
        fi
        card_change=false
    fi
    
done < <(pactl subscribe | stdbuf -oL grep -e "Event 'change' on sink #" -e "Event 'change' on card #")

